addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.6.2")
addSbtPlugin("org.playframework" % "sbt-plugin"          % "3.0.11")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.12.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.7.0")
// addSbtPlugin("com.github.sbt" % "sbt-javaagent" % "0.1.8")
